import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { render, screen } from '@/test/test-utils'
import userEvent from '@testing-library/user-event'
const mocks = vi.hoisted(() => ({ encrypt: vi.fn(), decrypt: vi.fn() }))
vi.mock('@/lib/crypto', () => mocks)
import { AccountHistoryExport } from '@/components/account-history-export'
beforeEach(() => {
  vi.resetAllMocks()
  mocks.encrypt.mockResolvedValue('encrypted-archive')
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json({ format: 'multillm-conversation-archive', version: 1, conversations: [], messages: [] })))
  vi.stubGlobal('URL', class extends URL {
    static createObjectURL = vi.fn().mockReturnValue('blob:archive')
    static revokeObjectURL = vi.fn()
  })
  vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {})
})
afterEach(() => { vi.unstubAllGlobals(); vi.restoreAllMocks() })
it('encrypts the owned server response before creating a downloadable file', async () => {
  const user = userEvent.setup()
  render(<AccountHistoryExport />)
  await user.type(screen.getByLabelText('Conversation archive password'), 'long-passphrase')
  await user.click(screen.getByRole('button', { name: 'Download conversation archive' }))
  expect(await screen.findByRole('status')).toHaveTextContent('Archive prepared')
  expect(mocks.encrypt).toHaveBeenCalledWith(expect.stringContaining('multillm-conversation-archive'), 'long-passphrase')
  expect(URL.createObjectURL).toHaveBeenCalledTimes(1)
  expect(URL.revokeObjectURL).toHaveBeenCalledWith('blob:archive')
})
it('does not download or show success when the server rejects an oversized archive', async () => {
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json({ error: 'Archive exceeds limit' }, { status: 413 })))
  const user = userEvent.setup()
  render(<AccountHistoryExport />)
  await user.type(screen.getByLabelText('Conversation archive password'), 'long-passphrase')
  await user.click(screen.getByRole('button', { name: 'Download conversation archive' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('exceeds limit')
  expect(URL.createObjectURL).not.toHaveBeenCalled()
  expect(mocks.encrypt).not.toHaveBeenCalled()
})

it('opens a valid encrypted archive locally without contacting the server', async () => {
  mocks.decrypt.mockResolvedValue(JSON.stringify({ format: 'multillm-conversation-archive', version: 1, conversations: [], messages: [] }))
  const user = userEvent.setup()
  render(<AccountHistoryExport />)
  const file = new File(['ciphertext'], 'history.encrypted', { type: 'text/plain' })
  Object.defineProperty(file, 'text', { value: async () => 'ciphertext' })
  await user.upload(screen.getByLabelText('Open an existing archive'), file)
  await user.type(screen.getByLabelText('Conversation archive password'), 'long-passphrase')
  await user.click(screen.getByRole('button', { name: 'Open archive as JSON' }))
  expect(mocks.decrypt).toHaveBeenCalledWith('ciphertext', 'long-passphrase')
  expect(URL.createObjectURL).toHaveBeenCalledTimes(1)
  expect(fetch).not.toHaveBeenCalled()
})
it('rejects an invalid archive without downloading it', async () => {
  mocks.decrypt.mockRejectedValue(new Error('Invalid password'))
  const user = userEvent.setup()
  render(<AccountHistoryExport />)
  const file = new File(['ciphertext'], 'history.encrypted', { type: 'text/plain' })
  Object.defineProperty(file, 'text', { value: async () => 'ciphertext' })
  await user.upload(screen.getByLabelText('Open an existing archive'), file)
  await user.type(screen.getByLabelText('Conversation archive password'), 'wrong-password')
  await user.click(screen.getByRole('button', { name: 'Open archive as JSON' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Unable to open archive')
  expect(URL.createObjectURL).not.toHaveBeenCalled()
  expect(fetch).not.toHaveBeenCalled()
})
